DIY_blog_project/DIY_blog_project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

DIY_blog_project/blog_app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import IndexView, RegistrationView, MyLoginView, AllBlogsView, BlogView, BloggerView, CommentView, \
    BloggerListView, show_base_template_view, MyProfileView, ProfileEditView, BlogEditView, DeleteBlogView, AddBlogView

app_name = 'blog_app'


urlpatterns = [
    path('base/', show_base_template_view, name='base'),
    path('', IndexView.as_view(), name='index'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='blog_app:index'), name='logout'),
    path('all_blogs/', AllBlogsView.as_view(), name='all_blogs'),
    path('blog/<int:pk>/', BlogView.as_view(), name='blog'),
    path('blog/<int:pk>/<int:blogger_pk>/', BlogView.as_view(), name='blog'),
    path('blogger/<int:pk>/', BloggerView.as_view(), name='blogger'),
    path('comment/<int:pk>/', CommentView.as_view(), name='comment'),
    path('bloggers/', BloggerListView.as_view(), name='bloggers'),
    path('profile/', MyProfileView.as_view(), name='profile'),
    path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'),
    path('edit_blog/<int:pk>/', BlogEditView.as_view(), name='edit_blog'),
    path('deleted/<int:pk>', DeleteBlogView.as_view(), name='deleted'),
    path('add_block/', AddBlogView.as_view(), name='add_blog'),
]

DIY_blog_project/blog_app/models.py
from django.contrib.auth.models import User
from django.db import models


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Profile(BaseModel):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=1000)
    phone_number = models.IntegerField()
    profile_photo = models.ImageField(upload_to='profile_photos/', null=True, blank=True)


class Blog(BaseModel):
    name = models.CharField(max_length=100)
    content = models.TextField(max_length=1500)
    blogger = models.ForeignKey(User, on_delete=models.CASCADE)
    publication_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Comment(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    publication_date = models.DateTimeField(auto_now_add=True)
    description = models.TextField(max_length=400)

DIY_blog_project/blog_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm

from .models import Blog


class UserRegistrationForm(UserCreationForm):
    bio = forms.CharField(widget=forms.Textarea, max_length=1000)
    phone_number = forms.IntegerField(max_value=99999999999999999999)
    profile_photo = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']


class CommentForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea, max_length=400)


class ProfileEditForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    profile_photo = forms.ImageField(required=False)
    phone_number = forms.IntegerField()
    bio = forms.CharField(widget=forms.Textarea, max_length=1000)


class BlogEditForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['name', 'content']

DIY_blog_project/blog_app/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.views.generic import ListView
from django.contrib.auth import logout

from .forms import UserRegistrationForm, CommentForm, ProfileEditForm, BlogEditForm
from .models import Profile, Blog, Comment, Profile


class IndexView(View):
    def get(self, request):
        return render(request, 'blog_app/index.html')


class RegistrationView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('blog_app:index')
        user_form = UserRegistrationForm()
        context = {
            'user_form': user_form
        }
        return render(request, 'blog_app/register.html', context=context)

    def post(self, request):
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            phone_number = user_form.cleaned_data.get('phone_number')
            profile_photo = user_form.cleaned_data.get('profile_photo')
            bio = user_form.cleaned_data.get('bio')
            Profile.objects.create(user=user, phone_number=phone_number, profile_photo=profile_photo, bio=bio)
            username = user_form.cleaned_data.get('username')
            password = user_form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('blog_app:index')
        else:
            context = {
                'user_form': user_form
            }
            return render(request, 'blog_app/register.html', context=context)


class MyLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'blog_app/login.html'

    def get_success_url(self):
        messages.success(self.request, 'You logged in successfully')
        return self.request.GET.get('next', reverse_lazy('blog_app:index'))

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid credentials')
        return self.render_to_response(self.get_context_data(form=form))


class AllBlogsView(View):
    def get(self, request):
        blogs = Blog.objects.order_by('-publication_date').select_related('blogger')
        paginator = Paginator(blogs, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'page_obj': page_obj
        }
        return render(request, 'blog_app/all_blogs.html', context=context)


class BlogView(View):
    def get(self, request, pk, blogger_pk=None):
        blog = Blog.objects.get(pk=pk)
        comments = Comment.objects.order_by('-publication_date').filter(blog_id=pk)
        context = {
            'blog': blog,
            'comments': comments,
        }
        if blogger_pk:
            blogger = User.objects.get(pk=blogger_pk)
            context['blogger'] = blogger
        return render(request, 'blog_app/blog.html', context=context)


class BloggerView(View):
    def get(self, request, pk):
        blogger = Profile.objects.get(user_id=pk)
        blogs = Blog.objects.order_by('-publication_date').filter(blogger_id=pk)
        context = {
            'blogger': blogger,
            'blogs': blogs,
        }
        return render(request, 'blog_app/blogger.html', context=context)


class CommentView(LoginRequiredMixin, View):
    def get(self, request, pk):
        form = CommentForm()
        context = {
            'form': form,
            'pk': pk,
        }
        return render(request, 'blog_app/comment.html', context=context)

    def post(self, request, pk):
        form = CommentForm(request.POST)
        context = {
            'form': form,
        }
        if form.is_valid():
            kwargs = {
                'user': request.user,
                'blog': Blog.objects.get(pk=pk),
                'description': form.cleaned_data.get('description')
            }
            Comment.objects.create(**kwargs)
            return redirect('blog_app:blog', pk)

        return render(request, 'blog_app/comment.html', context=context)


# class BloggerListView(ListView):
#     model = Blog
#     template_name = 'blog_app/bloggers.html'
#     context_object_name = 'blogs'
#     paginate_by = 5


class BloggerListView(View):
    def get(self, request):
        # bloggers = Blog.objects.all().values('blogger').distinct()
        blogs = Blog.objects.all().select_related('blogger')
        bloggers = list()
        for blog in blogs:
            user = User.objects.get(pk=blog.blogger_id)
            if user not in bloggers:
                bloggers.append(user)

        paginator = Paginator(bloggers, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context = {
            'bloggers': page_obj,
        }
        return render(request, 'blog_app/bloggers.html', context=context)


def show_base_template_view(request):
    return render(request, 'blog_app/base.html')


class MyProfileView(LoginRequiredMixin, View):
    def get(self, request):
        profile = Profile.objects.get(user_id=request.user.pk)
        blogs = Blog.objects.filter(blogger_id=request.user.pk).all()
        context = {
            'profile': profile,
            'blogs': blogs,
        }
        return render(request, 'blog_app/my_profile.html', context=context)


class ProfileEditView(LoginRequiredMixin, View):
    def get(self, request):
        first_name = request.user.first_name
        last_name = request.user.last_name

        profile = Profile.objects.get(user_id=request.user.pk)
        phone_number = profile.phone_number
        bio = profile.bio

        user_kwargs = {
            'first_name': first_name,
            'last_name': last_name,
            'phone_number': phone_number,
            'bio': bio,
        }
        form = ProfileEditForm(initial={**user_kwargs})
        context = {
            'form': form,
        }
        return render(request, 'blog_app/edit_profile.html', context=context)

    def post(self, request):
        form = ProfileEditForm(request.POST, request.FILES)
        context = {
            'form': form,
        }
        if form.is_valid():
            user_kwargs = {
                'first_name': form.cleaned_data.get('first_name'),
                'last_name': form.cleaned_data.get('last_name'),
            }

            profile_kwargs = {
                'phone_number': form.cleaned_data.get('phone_number'),
                'bio': form.cleaned_data.get('bio'),
            }

            if form.cleaned_data.get('profile_photo'):
                profile = Profile.objects.get(user_id=request.user.pk)
                profile.profile_photo = form.cleaned_data.get('profile_photo')
                profile.save()

            User.objects.filter(pk=request.user.pk).update(**user_kwargs)
            Profile.objects.filter(user_id=request.user.pk).update(**profile_kwargs)
            return redirect('blog_app:profile')

        return render(request, 'blog_app/edit_profile.html', context=context)


class BlogEditView(View):
    def get(self, request, pk):
        blog = Blog.objects.get(pk=pk)

        if blog.blogger_id != request.user.pk:
            raise PermissionDenied()

        form = BlogEditForm(initial={'name': blog.name, 'content': blog.content})
        context = {
            'form': form,
            'pk': pk,
        }

        return render(request, 'blog_app/edit_blog.html', context=context)

    def post(self, request, pk):
        form = BlogEditForm(request.POST)
        context = {
            'form': form,
        }

        if form.is_valid():
            kwargs = {
                'name': form.cleaned_data.get('name'),
                'content': form.cleaned_data.get('content'),
            }
            Blog.objects.filter(pk=pk).update(**kwargs)
            return redirect('blog_app:blog', *(pk, request.user.pk))

        return render(request, 'blog_app/edit_blog.html', context=context)


class DeleteBlogView(View):
    def post(self, request, pk):
        blog = Blog.objects.filter(pk=pk)
        context = {
            'blog': blog,
        }
        blog.delete()
        return render(request, 'blog_app/deleted.html', context=context)


class AddBlogView(View):
    def get(self, request):
        form = BlogEditForm()
        context = {
            'form': form,
        }
        return render(request, 'blog_app/add_blog.html', context=context)

    def post(self, request):
        form = BlogEditForm(request.POST)
        context = {
            'form': form,
        }
        if form.is_valid():
            kwargs = {
                'name': form.cleaned_data.get('name'),
                'content': form.cleaned_data.get('content'),
                'blogger': request.user
            }
            blog = Blog.objects.create(**kwargs)
            return redirect('blog_app:blog', pk=blog.pk)

        return render(request, 'blog_app:add_blog', context=context)

DIY_blog_project/blog_app/templates/blog_app/add_blog.html
{% extends 'blog_app/base.html' %}

{% block title %}
    Add blog
{% endblock %}

{% block content %}
    <h1 class="content_title">Add blog</h1>
    <form method="post" class="content_inner">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/all_blogs.html
{% extends 'blog_app/base.html' %}

{% block title %}
    All blogs
{% endblock %}

{% block content %}
    <h1 class='content_title'>All blogs</h1>
    <div style="vertical-align: middle; height: auto; width: auto; margin: 5px">
        <ul>
            {% for obj in page_obj %}
                <li><a class='blog' href="{% url 'blog_app:blog' obj.pk %}">{{ obj }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <nav class='navigation'>
        {% for p in page_obj.paginator.page_range %}
            <a href="?page={{ p }}">{{ p }}</a>
        {% endfor %}
    </nav>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
</head>
<body>
    <div class='wrapper'>
        <div class='links_wrapper'>
            {% block base_links %}
                <div class="link_setup">
                    <a class='link' href='{% url "blog_app:index" %}'>Home</a>
                    <a class='link' href='{% url "blog_app:all_blogs" %}'>All blogs</a>
                    <a class='link' href='{% url "blog_app:bloggers" %}'>All bloggers</a>
                    {% if request.user.is_authenticated %}
                        <a class='link' href='{% url "blog_app:profile" %}'>My profile</a>
                    {% endif %}
                </div>
            {% endblock %}
            {% block in_out %}
                <div class="login_logout_set" >
                    {% if request.user.is_authenticated %}
                        <div class="display_username">Username: {{ request.user.first_name }}</div>
                        <form method="post" action="{% url 'blog_app:logout' %}">
                            {% csrf_token %}
                            <button type="submit">logout</button>
                        </form>
                    {% else %}
                        <a class='link' href="{% url 'blog_app:login' %}">Sing in</a>
                        <a class='link' href="{% url 'blog_app:registration' %}">Sign up</a>
                    {% endif %}
                </div>
            {% endblock %}
        </div>
        <div class='content'>
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

DIY_blog_project/blog_app/templates/blog_app/blog.html
{% extends 'blog_app/base.html' %}

{% block title %}
    {{ blog.name }}
{% endblock %}

{% block content %}
    <h1 class="content_title">{{ blog.name }}</h1>
    <div class="content_inner">
        <p><b>Post date</b>: {{ blog.publication_date }}</p>
        <p><b>Author</b>: {{ blog.blogger.username }}</p>
        <p><b>Description</b>: {{ blog.content }}</p>
        <br><br>
        {% if comments %}
            <p>Comments</p>
            <ul>
                {% for comment in comments %}
                    <li>{{ comment.user.username }} ({{ comment.publication_date }}) - {{ comment.description }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No comments yet</p>
        {% endif %}
        {% if request.user.is_authenticated %}
            <a class="content_inner_links" href="{% url 'blog_app:comment' blog.pk %}">Add a new comment</a><br><br>
        {% endif %}
        {% if blogger %}
            <a class="content_inner_links" href="{% url 'blog_app:blogger' blogger.pk %}">{{ blogger.username }}</a>
            <br><br>
        {% endif %}
    </div>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/blogger.html
{% extends 'blog_app/base.html' %}
{%load static%}

{% block title %}
    {{ author.username }}
{% endblock %}

{% block content %}
    <h1 class="content_title">Blogger: {{ blogger.user.username }}</h1>
    <div class="content_inner">
        <p>{{ blogger.user.first_name }} {{ blogger.user.last_name }}</p>
        {% if blogger.profile_photo %}
            <p><img class="profile_photo" src="{{ blogger.profile_photo.url }}" alt="Profile photo"></p>
        {% else %}
            <p><img class="profile_photo" src="/media/profile_photos/default.jpg" alt="Profile photo"></p>
        {% endif %}
        <h2>Bio: {{ blogger.bio }}</h2>
        <ul>
            {% for blog in blogs %}
                <li><a class="content_inner_links" href="{% url 'blog_app:blog' blog.pk blogger.user_id %}">{{ blog }}</a> ({{ blog.publication_date }})</li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/bloggers.html
{% extends 'blog_app/base.html' %}

{% block title %}
    Bloggers
{% endblock %}

{% block content %}
    <h1 class="content_title">All bloggers</h1>
    <ul>
        {% for blogger in bloggers %}
            <li><a class='blog' href="{% url 'blog_app:blogger' blogger.pk %}">{{ blogger }}</a></li>
        {% endfor %}
    </ul>
    <nav class='navigation'>
        {% for p in bloggers.paginator.page_range %}
            <a href="?page={{ p }}">{{ p }}</a>
        {% endfor %}
    </nav>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/comment.html
{% extends 'blog_app/base.html' %}

{% block title %}
  Add comment
{% endblock %}


{% block content %}
    <h1 class="content_title">Add comment</h1>
    <form method="post" class="content_inner">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Submit</button>
    </form>
    <br>
    <a class="content_inner_links" href="{% url 'blog_app:blog' pk %}">Back to blog</a>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/deleted.html
{% extends 'blog_app/base.html' %}

{% block title %}
    Deleted
{% endblock %}

{% block content %}
    <h1 class="content_title">Blog has been deleted</h1>
    <div class="content_inner">
        Blog has been successfully deleted
    </div>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/edit_blog.html
{% extends 'blog_app/base.html' %}

{% block title %}
    Edit blog
{% endblock %}

{% block content %}
    <h1 class="content_title">Edit blog</h1>
    <div class="content_inner">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
        </form>
        <form action="{% url 'blog_app:deleted' pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
    </div>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/edit_profile.html
{% extends 'blog_app/base.html' %}

{% block title %}
    Edit profile
{% endblock %}

{% block content %}
    <h1 class="content_title">Edit profile</h1>
    <form class='content_inner' method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/index.html
{% extends 'blog_app/base.html' %}

{% block content %}
    <h1 class="content_title">Homepage</h1>
    <div class="content_inner">
        The project was created as a design work to solve the tasks indicated on the site
        <a style="text-decoration: none; color: #0071c5; font-family: 'Inter', sans-serif;" href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/django_assessment_blog">
            developer.mozilla.org
        </a>
    </div>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/login.html
{% extends 'blog_app/base.html' %}

{% block title %}
    Страница входа
{% endblock %}

{% block base_links %}
{% endblock %}

{% block in_out %}
{% endblock %}

{% block content %}
  <div class="center">
	  <form method="post" class="card" novalidate>
	  	{% csrf_token %}
	    <h2 class="text-center">Log in to your account</h2>
		{% for field in form %}
	    		{{ field.label_tag }}
	        	{{ field }}
		{% endfor %}
		<input type="submit" value="Login" class="btn btn-primary full-width">
		<hr>
		{% if messages %}
			{% for message in messages %}
				<small style='color:red'>{{ message }}</small>
			{% endfor %}
		{% endif %}
		<p class="text-center">Turn to the main page <a href="{% url 'blog_app:index' %}">Index</a></p>
		<p class="text-center">Don't have an account? <a href="{% url 'blog_app:registration' %}">Join Now</a></p>
	</form>
  </div>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/my_profile.html
{% extends 'blog_app/base.html' %}

{% block title %}
    Profile
{% endblock %}

{% block content %}
    <h1 class="content_title">Profile</h1>
    <div class="content_inner">
        <b>Username:</b> {{ profile.user }}
        <p>{{ request.user.first_name }} {{ request.user.last_name }}</p>
        {% if profile.profile_photo %}
            <p><img class="profile_photo" src="{{ profile.profile_photo.url }}" alt="Profile photo"></p>
        {% else %}
            <p><img class="profile_photo" src="/media/profile_photos/default.jpg" alt="Default photo"></p>
        {% endif %}
        <p><b>Phone:</b> +{{ profile.phone_number }}</p>
        <p><b>Bio:</b> {{ profile.bio }}</p>
        <a class="link" href="{% url 'blog_app:edit_profile' %}">Edit profile data</a>
        <p><b>Blogs:</b></p>
        {% if blogs %}
            <ul>
                {% for blog in blogs %}
                    <li><a class="link" href="{% url 'blog_app:edit_blog' blog.pk %}">{{ blog }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            &emsp;&emsp;Not posted yet
        {% endif %}
        <a class="link" href="{% url 'blog_app:add_blog' %}">Add blog</a>
    </div>
{% endblock %}

DIY_blog_project/blog_app/templates/blog_app/register.html
{% extends 'blog_app/base.html' %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}
    <h1 class="content_title">Registration</h1>
    <form class='content_inner' method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        <button type="submit">Create</button>
    </form>
{% endblock %}